# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'queuehubMobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for queuehubMobile

  target 'queuehubMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'queuehubMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
